// Copyright (C) Hygon Info Technologies Ltd.
//
// SPDX-License-Identifier: Apache-2.0
//

use crate::error::*;
use crate::{
    certs::{csv::Certificate, Usage, Verifiable},
    crypto::{sig::ecdsa, PublicKey, Signature},
    util::*,
};

use openssl::{
    hash::{Hasher, MessageDigest},
    pkey, sign,
};

use static_assertions::const_assert;

use serde::{Deserialize, Serialize};
use serde_big_array::BigArray;
use std::io::Write;

use bitfield::bitfield;

#[repr(C)]
#[derive(Default, Debug, PartialEq)]
pub struct AttestationRequest {
    pub mnonce: [u8; 16],
}

/// Data provided by the guest owner for requesting an attestation report
/// from the HYGON Secure Processor.
#[repr(C)]
#[derive(Default, Debug, PartialEq)]
pub struct ReportReq {
    pub req: AttestationRequest,
}

impl ReportReq {
    pub fn new(mnonce: Option<[u8; 16]>) -> Result<Self, Error> {
        let mut request = Self::default();

        request.req.mnonce = mnonce.unwrap_or_else(|| {
            let mut rng = rand::thread_rng();
            let mut random_mnonce = [0u8; 16];
            rng.fill(&mut random_mnonce);
            random_mnonce
        });

        Ok(request)
    }
}

#[repr(C)]
struct MkfdIoctlSecurityAttestationArgs {
    gpu_id: u32,
    version: u32,
    request_data: *mut c_void,
    request_size: u64,
    response_data: *mut c_void,
    response_size: u64,
    fw_err: u64,
}

#[repr(C)]
#[derive(Debug, Copy, Clone, Serialize, Deserialize)]
pub struct Body {
    pub version: u32,
    pub chip_id: [u8; 16],
    pub mnonce: [u8; 16],
    pub measure: [u8; 32],
}

impl Default for Body {
    fn default() -> Self {
        Self {
            version: Default::default(),
            chip_id: Default::default(),
            mnonce: Default::default(),
            measure: Default::default(),
        }
    }
}

/// Data provieded by the guest owner for requesting an attestation report
/// from the HYGON Secure Processor.
#[repr(C)]
#[derive(Debug, Serialize, Deserialize)]
pub struct AttestationReport {
    pub body: Body,
    pub sig_usage: u32,
    pub sig_algo: u32,
    pub sig: ecdsa::Signature,
}

impl Default for AttestationReport {
    fn default() -> Self {
        Self {
            body: Default::default(),
            sig_usage: Default::default(),
            sig_algo: Default::default(),
            anonce: Default::default(),
            sig: Default::default(),
        }
    }
}

#[repr(C)]
pub struct AttestationResponse {
    report_size: u32,
    reserved: [u8; 28],
    pub report: AttestationReport,
}

/// The response from the PSP containing the generated attestation report.
///
/// The Report is padded to exactly 4096 Bytes to make sure the page size
/// matches.
#[repr(C)]
pub struct ReportRsp {
    /// The attestation report generated by the firmware.
    pub response: AttestationResponse
}

// Compile-time check that the size is what is expected.
const_assert!(std::mem::size_of::<ReportRsp>() == 4096);

impl Default for ReportRsp {
    fn default() -> Self {
        Self {
            response: response::default(),
    }
}
}
impl codicon::Encoder<crate::Body> for AttestationReport {
    type Error = std::io::Error;

    fn encode(&self, mut writer: impl Write, _: crate::Body) -> Result<(), std::io::Error> {
        writer.save(&self.body)
    }
}

impl TryFrom<&AttestationReport> for Signature {
    type Error = std::io::Error;

    #[inline]
    fn try_from(value: &AttestationReport) -> Result<Self, std::io::Error> {
        let sig = Vec::try_from(&value.sig)?;
        Ok(Self {
            sig,
            id: None,
            usage: Usage::PEK.into(),
            algo: None,
        })
    }
}

impl Verifiable for (&Certificate, &AttestationReport) {
    type Output = ();

    fn verify(self) -> Result<(), std::io::Error> {
        let key: PublicKey = self.0.try_into()?;
        let sig: Signature = self.1.try_into()?;
        key.verify(
            self.1,
            &self.0.body.data.user_id[..self.0.body.data.uid_size as usize],
            &sig,
        )
    }
}

#[cfg(test)]
mod test {
    mod report_req {
        use crate::api::dcu::types::ReportReq;
        #[test]
        pub fn test_new() {
            let data: [u8; 64] = [
                103, 198, 105, 115, 81, 255, 74, 236, 41, 205, 186, 171, 242, 251, 227, 70, 124,
                194, 84, 248, 27, 232, 231, 141, 118, 90, 46, 99, 51, 159, 201, 154, 102, 50, 13,
                183, 49, 88, 163, 90, 37, 93, 5, 23, 88, 233, 94, 212, 171, 178, 205, 198, 155,
                180, 84, 17, 14, 130, 116, 65, 33, 61, 220, 135,
            ];
            let mnonce: [u8; 16] = [
                112, 233, 62, 161, 65, 225, 252, 103, 62, 1, 126, 151, 234, 220, 107, 150,
            ];
            let hash: [u8; 32] = [
                19, 76, 8, 98, 33, 246, 247, 155, 28, 21, 245, 185, 118, 74, 162, 128, 82, 15, 160,
                233, 212, 130, 106, 177, 89, 6, 119, 243, 130, 21, 3, 153,
            ];
            let expected: ReportReq = ReportReq { data, mnonce, hash };

            let actual: ReportReq = ReportReq::new(Some(data), mnonce).unwrap();

            assert_eq!(expected, actual);
        }

        #[test]
        #[should_panic]
        pub fn test_new_error() {
            let data: [u8; 64] = [
                103, 198, 105, 115, 81, 255, 74, 236, 41, 205, 186, 171, 242, 251, 227, 70, 124,
                194, 84, 248, 27, 232, 231, 141, 118, 90, 46, 99, 51, 159, 201, 154, 102, 50, 13,
                183, 49, 88, 163, 90, 37, 93, 5, 23, 88, 233, 94, 212, 171, 178, 205, 198, 155,
                180, 84, 17, 14, 130, 116, 65, 33, 61, 220, 135,
            ];
            let mnonce: [u8; 16] = [
                112, 233, 62, 161, 65, 225, 252, 103, 62, 1, 126, 151, 234, 220, 107, 150,
            ];
            let wrong_mnonce: [u8; 16] = [
                0, 233, 62, 161, 65, 225, 252, 103, 62, 1, 126, 151, 234, 220, 107, 150,
            ];
            let hash: [u8; 32] = [
                19, 76, 8, 98, 33, 246, 247, 155, 28, 21, 245, 185, 118, 74, 162, 128, 82, 15, 160,
                233, 212, 130, 106, 177, 89, 6, 119, 243, 130, 21, 3, 153,
            ];
            let expected: ReportReq = ReportReq { data, mnonce, hash };

            let actual: ReportReq = ReportReq::new(Some(data), wrong_mnonce).unwrap();

            assert_eq!(expected, actual);
        }
    }
}
